# Generated by Django 3.1.2 on 2021-06-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Transport_date', models.DateField()),
                ('booking_status', models.CharField(max_length=11)),
                ('booking_status2', models.CharField(max_length=11)),
                ('payment_status', models.CharField(max_length=11)),
                ('from_location', models.CharField(max_length=30)),
                ('to_location', models.CharField(max_length=30)),
                ('quotation_amount', models.FloatField()),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=75)),
                ('landmark', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=75)),
                ('landmark', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=11)),
                ('is_admin', models.IntegerField(default=0)),
                ('OTP', models.CharField(max_length=10, null=True)),
                ('OTP_used', models.IntegerField(default=0)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.area')),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mpm.company')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_category_name', models.CharField(max_length=30)),
                ('service_image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Service_category',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('TransportCompany_id', models.AutoField(primary_key=True, serialize=False)),
                ('TransportCompany_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=13)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=75)),
                ('landmark', models.CharField(max_length=30)),
                ('licence_no', models.CharField(max_length=20)),
                ('TransportCompany_image', models.FileField(upload_to='')),
                ('reg_start_date', models.DateField()),
                ('reg_end_date', models.DateField()),
            ],
            options={
                'db_table': 'TransportCompany',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_category',
            fields=[
                ('vehicle_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_category_name', models.CharField(max_length=30)),
                ('vehicle_image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Vehicle_category',
            },
        ),
        migrations.CreateModel(
            name='TransportCompany_Vehicle_category',
            fields=[
                ('TransportCompany_Vehicle_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('rateperKM', models.FloatField()),
                ('TransportCompany_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany')),
                ('Vehicle_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.vehicle_category')),
            ],
            options={
                'db_table': 'TransportCompany_Vehicle_category',
            },
        ),
        migrations.CreateModel(
            name='TransportCompany_Service_category',
            fields=[
                ('TransportCompany_Service_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('TransportCompany_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany')),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.service_category')),
            ],
            options={
                'db_table': 'TransportCompany_Service_category',
            },
        ),
        migrations.CreateModel(
            name='TransportCompany_package',
            fields=[
                ('TransportCompany_pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('TransportCompany_pk_name', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
                ('description', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mpm.company')),
            ],
            options={
                'db_table': 'TransportCompany_package',
            },
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='TransportCompany_pk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany_package'),
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.area'),
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mpm.company'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
                ('TransportCompany_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany')),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.service_category')),
            ],
            options={
                'db_table': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('gallry_path', models.FileField(upload_to='')),
                ('TransportCompany_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany')),
            ],
            options={
                'db_table': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('TransportCompany_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.customer')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=13)),
                ('addressline1', models.CharField(max_length=100)),
                ('addressline2', models.CharField(max_length=75)),
                ('landmark', models.CharField(max_length=30)),
                ('license_image', models.FileField(upload_to='')),
                ('TransportCompany_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany')),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.state')),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Booking_detail',
            fields=[
                ('booking_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.booking')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.product')),
            ],
            options={
                'db_table': 'Booking_detail',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='TransportCompany_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.transportcompany'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mpm.driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mpm.vehicle_category'),
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mpm.city'),
        ),
    ]
