# Generated by Django 2.2.2 on 2022-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='OTP',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transportcompany',
            name='OTP_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='OTP',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
