# Generated by Django 2.2.2 on 2022-04-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpm', '0002_auto_20220428_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportcompany',
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='transportcompany',
            name='OTP_used',
        ),
    ]
